# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rrank <- function(A, tol) {
    .Call('_hrt_rrank', PACKAGE = 'hrt', A, tol)
}

rkernel <- function(A, tol) {
    .Call('_hrt_rkernel', PACKAGE = 'hrt', A, tol)
}

ctest <- function(umat, Rbmat, Wvec, Bmat, cores, tol) {
    .Call('_hrt_ctest', PACKAGE = 'hrt', umat, Rbmat, Wvec, Bmat, cores, tol)
}

